apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  labels:
    app: argo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-demo
  template:
    metadata:
      labels:
        app: argo-demo
    spec:
      containers:
      - name: argo-demo
        image: aartread/argo-demo:v2
        ports:
        - containerPort: 80